# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Josh Bruen
title: Test Automation Engineer
email: jbruen17@gmail.com
website: www.github.com/Xeno828

# Social links
twitter_username: JustJoshnRound
github_username:  Xeno828
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: josh.bruen
linkedin_username: JoshBruen
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Josh and I'm a Test automation engineer. As well as performing, writting and maintaining automation scenarios I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>BDD Language</mark> and <mark>Java</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Automation and web design some of my other interests and hobbies are:
   - Anime
   - Fortnite
   - Completing Adventure runs
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
